# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11lf6Z8BSSlB-DuivKDJ7Kj61NgBcB1nv
"""

year = int(input('Enter the year: '))
if (year%4 == 0 and year%100!= 0) or year%400 == 0:
  print('leap year')
else:
  print('not a leap year')
input()